on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
          
    - name: Iniciar Proyecto
      run: | 
        mkdir EstoESunArchivo
        cd EstoESunArchivo
        echo "gato" > text.txt
        pwd
        ls
        
