on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: $
      # Este comando es solo un ejemplo para mostrar cómo se imprime tu secreto.
      # Asegúrate de eliminar las declaraciones impresas de tus secretos. GitHub 
      # no oculta los secretos que usan esta solución.
      - name: Test printing your secret (Elimina este paso en la producción)
        run: cat $HOME/secrets/my_secret.json
        
