on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      - name: check
        uses: actions/checkout@v1
      
      - name: Build
        run: |
          npm install
          
       
        
